### ISSUE TITLE
咨询训练时间

### ISSUE THREAD

**Issue by tongshoujie** [yxuansu/TaCL#13]
作者你好，感谢你的开源
请教一下，预训练150k，你大概用了多长时间呀？

**Comment by yxuansu** [comment]
> 作者你好，感谢你的开源 请教一下，预训练150k，你大概用了多长时间呀？

同学你好，

对于base模型的话，训练时间大概在40个小时左右（也和GPU型号及个数有关）。

**Comment by tongshoujie** [comment]
> > 作者你好，感谢你的开源 请教一下，预训练150k，你大概用了多长时间呀？
> 
> 同学你好，
> 
> 对于base模型的话，训练时间大概在40个小时左右（也和GPU型号及个数有关）。

感谢你的回答
