### ISSUE TITLE
这个数据量是不是不太对？

### ISSUE THREAD

**Issue by tongshoujie** [yxuansu/TaCL#14]
作者你好，如图，这个数据量是不是不太对？
<img width="212" alt="image" src="https://user-images.githubusercontent.com/49876698/166716225-f2bed34a-f2dc-43c5-b3c9-20db1adc052a.png">

**Comment by yxuansu** [comment]
> 作者你好，如图，这个数据量是不是不太对？ <img alt="image" width="212" src="https://user-images.githubusercontent.com/49876698/166716225-f2bed34a-f2dc-43c5-b3c9-20db1adc052a.png">

Hi,

请查看这个函数哈( https://github.com/yxuansu/TaCL/blob/d92e47cfa3c24d9b674423a01b3e4216a6b62891/pretraining/google_bert.py#L164 )。
这个是摘自谷歌的代码，构建数据有一定随机情况所以数字有可能对不上。

**Comment by tongshoujie** [comment]
> > 作者你好，如图，这个数据量是不是不太对？ <img alt="image" width="212" src="https://user-images.githubusercontent.com/49876698/166716225-f2bed34a-f2dc-43c5-b3c9-20db1adc052a.png">
> 
> Hi,
> 
> 请查看这个函数哈(
> 
> https://github.com/yxuansu/TaCL/blob/d92e47cfa3c24d9b674423a01b3e4216a6b62891/pretraining/google_bert.py#L164
> 
> )。
> 这个是摘自谷歌的代码，构建数据有一定随机情况所以数字有可能对不上。

感谢回答
