### ISSUE TITLE
Hello, have you tired the roberta model?

### ISSUE THREAD

**Issue by junleiz** [yxuansu/TaCL#3]
As you have compared your results with SimCSE, which evaluate their method on Bert and RoBerta. Could you please tell me whether you have tired your method on roberta. In many cases, methods work on bert can not improve the performance of roberta.

**Comment by yxuansu** [comment]
> As you have compared your results with SimCSE, which evaluate their method on Bert and RoBerta. Could you please tell me whether you have tired your method on roberta. In many cases, methods work on bert can not improve the performance of roberta.

Hi, 

Thank you for your interest in our paper. In this work, we mainly focus on testing our approach on BERT. We will update the paper in the future if we test our approach with Roberta.
