### ISSUE TITLE
how can i get the embedding ?

### ISSUE THREAD

**Issue by mathshangw** [yxuansu/TaCL#6]
excuse me how can I extract_embeddings for specific sentences using your model . I used for example keras-bert and it has already a function called extract_embeddings as I need to make your model as an embedding layer using keras.
Appreciate your help , Thanks

**Comment by yxuansu** [comment]
> excuse me how can I extract_embeddings for specific sentences using your model . I used for example keras-bert and it has already a function called extract_embeddings as I need to make your model as an embedding layer using keras. Appreciate your help , Thanks

Hi, thank you for your interest in our work. Could you be more specific on which layer's embedding you would like to extract?

**Comment by yxuansu** [comment]
Feel free to reopen the issue.

**Comment by mathshangw** [comment]
sorry for the late reply , i need to extract word-embedding
