### ISSUE TITLE
How can i extract word-embedding

### ISSUE THREAD

**Issue by mathshangw** [yxuansu/TaCL#8]
sorry for the late reply , i need to extract word-embedding

_Originally posted by @mathshangw in https://github.com/yxuansu/TaCL/issues/6#issuecomment-1005028932_

**Comment by yxuansu** [comment]
> sorry for the late reply , i need to extract word-embedding
> 
> _Originally posted by @mathshangw in [#6 (comment)](https://github.com/yxuansu/TaCL/issues/6#issuecomment-1005028932)_

Hi,

You can refer to this [line](https://github.com/yxuansu/TaCL/blob/e5fc4681fc7053f25c46a4fec410696e3562c3c4/analysis/layerwise_intra_sentence_similarity.py#L43) to extract the features from TaCL. The attention_hidden_states[0] is the word embedding that you want.

**Comment by mathshangw** [comment]
Thanks for replying and sorry for my late reply. i get that BERT work on sub-words basically but my problem is to get the word-embedding how it could be calculated or does the line you mentioned is for word, not sub-word embedding , please?
